source/Deli Menu/Deli Menu/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Deli_Menu.Models;

namespace Deli_Menu.Controllers
{
    public class CategoriesController : Controller
    {
        private DeliDatabaseContext db = new DeliDatabaseContext();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

source/Deli Menu/Deli Menu/Controllers/FoodItemCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Deli_Menu.Models;

namespace Deli_Menu.Controllers
{
    public class FoodItemCategoriesController : Controller
    {
        private DeliDatabaseContext db = new DeliDatabaseContext();

        // GET: FoodItemCategories
        public ActionResult Index()
        {
            var foodItemCategories = db.FoodItemCategories.Include(f => f.Category).Include(f => f.FoodItem);
            return View(foodItemCategories.ToList());
        }

        // GET: FoodItemCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodItemCategory foodItemCategory = db.FoodItemCategories.Find(id);
            if (foodItemCategory == null)
            {
                return HttpNotFound();
            }
            return View(foodItemCategory);
        }

        // GET: FoodItemCategories/Create
        public ActionResult Create()
        {
            ViewBag.FoodCategoryID = new SelectList(db.Categories, "ID", "CategoryName");
            ViewBag.FoodItemID = new SelectList(db.FoodItems, "ID", "ItemName");
            return View();
        }

        // POST: FoodItemCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FoodItemID,FoodCategoryID")] FoodItemCategory foodItemCategory)
        {
            if (ModelState.IsValid)
            {
                db.FoodItemCategories.Add(foodItemCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FoodCategoryID = new SelectList(db.Categories, "ID", "CategoryName", foodItemCategory.FoodCategoryID);
            ViewBag.FoodItemID = new SelectList(db.FoodItems, "ID", "ItemName", foodItemCategory.FoodItemID);
            return View(foodItemCategory);
        }

        // GET: FoodItemCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodItemCategory foodItemCategory = db.FoodItemCategories.Find(id);
            if (foodItemCategory == null)
            {
                return HttpNotFound();
            }
            ViewBag.FoodCategoryID = new SelectList(db.Categories, "ID", "CategoryName", foodItemCategory.FoodCategoryID);
            ViewBag.FoodItemID = new SelectList(db.FoodItems, "ID", "ItemName", foodItemCategory.FoodItemID);
            return View(foodItemCategory);
        }

        // POST: FoodItemCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FoodItemID,FoodCategoryID")] FoodItemCategory foodItemCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(foodItemCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FoodCategoryID = new SelectList(db.Categories, "ID", "CategoryName", foodItemCategory.FoodCategoryID);
            ViewBag.FoodItemID = new SelectList(db.FoodItems, "ID", "ItemName", foodItemCategory.FoodItemID);
            return View(foodItemCategory);
        }

        // GET: FoodItemCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodItemCategory foodItemCategory = db.FoodItemCategories.Find(id);
            if (foodItemCategory == null)
            {
                return HttpNotFound();
            }
            return View(foodItemCategory);
        }

        // POST: FoodItemCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FoodItemCategory foodItemCategory = db.FoodItemCategories.Find(id);
            db.FoodItemCategories.Remove(foodItemCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

source/Deli Menu/Deli Menu/Controllers/FoodItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Deli_Menu.Models;

namespace Deli_Menu.Controllers
{
    public class FoodItemsController : Controller
    {
        private DeliDatabaseContext db = new DeliDatabaseContext();

        // GET: FoodItems
        public ActionResult Index()
        {
            return View(db.FoodItems.ToList());
        }

        // GET: FoodItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodItem foodItem = db.FoodItems.Find(id);
            if (foodItem == null)
            {
                return HttpNotFound();
            }
            return View(foodItem);
        }

        // GET: FoodItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FoodItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ItemName,ServingSize,ServingsContained,Calories,TotalFat,SaturatedFat,TransFat,Colesterol,Sodium,TotalCarbohydrate,DietaryFiber,TotalSugars,AddedSugars,Protien,A,C,Calcuim,Iron,D,E,K,Thiamin,Ribolavin,Niacin,Folate,B12,Biotin,PantothenicAcid,Phosphorus,Iodine,Magnesium,Zinc,Selenium,Copper,Manganese,Chromium,Molybdenum,Chloride")] FoodItem foodItem)
        {
            if (ModelState.IsValid)
            {
                db.FoodItems.Add(foodItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(foodItem);
        }

        // GET: FoodItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodItem foodItem = db.FoodItems.Find(id);
            if (foodItem == null)
            {
                return HttpNotFound();
            }
            return View(foodItem);
        }

        // POST: FoodItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ItemName,ServingSize,ServingsContained,Calories,TotalFat,SaturatedFat,TransFat,Colesterol,Sodium,TotalCarbohydrate,DietaryFiber,TotalSugars,AddedSugars,Protien,A,C,Calcuim,Iron,D,E,K,Thiamin,Ribolavin,Niacin,Folate,B12,Biotin,PantothenicAcid,Phosphorus,Iodine,Magnesium,Zinc,Selenium,Copper,Manganese,Chromium,Molybdenum,Chloride")] FoodItem foodItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(foodItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(foodItem);
        }

        // GET: FoodItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodItem foodItem = db.FoodItems.Find(id);
            if (foodItem == null)
            {
                return HttpNotFound();
            }
            return View(foodItem);
        }

        // POST: FoodItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FoodItem foodItem = db.FoodItems.Find(id);
            db.FoodItems.Remove(foodItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

source/Deli Menu/Deli Menu/Controllers/HomeController.cs
using Deli_Menu.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Deli_Menu.Controllers
{
    public class HomeController : Controller
    {
        private DeliDatabaseContext db = new DeliDatabaseContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Menu()
        {
            return View(db.FoodItems.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        // Admin Demo View
        public ActionResult Admin()
        {
            return View();
        }

        // GET: Home/Item/5
        public ActionResult Item(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodItem foodItem = db.FoodItems.Find(id);
            if (foodItem == null)
            {
                return HttpNotFound();
            }
            return View(foodItem);
        }
    }
}

source/Deli Menu/Deli Menu/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

source/Deli Menu/Deli Menu/Views/Home/Admin.cshtml

@{
    ViewBag.Title = "Admin";
}

<h2>Admin</h2>
<p>This is a demonstration page for administrators. It contains links to management demonstration pages.</p>
<p>
    <ul>
        <li>@Html.ActionLink("Food Items", "Index", "FoodItems")</li>
        <li>@Html.ActionLink("Food Categories", "Index", "Categories")</li>
        <li>@Html.ActionLink("Food Category Relations", "Index", "FoodItemCategories")</li>
    </ul>
</p>


source/Deli Menu/Deli Menu/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

source/Deli Menu/Deli Menu/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="text-center">
    <div id="homeCarousel" class="carousel slide" style="width: 784px; margin-right: auto; margin-left: auto" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#homeCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#homeCarousel" data-slide-to="1"></li>
            <li data-target="#homeCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img class="img-responsive" src="~/Content/Images/tuckin-holiday-party-2017-II.jpg" />
            </div>

            <div class="item">
                <img class="img-responsive" src="~/Content/Images/tuckin-holiday-platter-II.jpg" />
            </div>

            <div class="item">
                <img class="img-responsive" src="~/Content/Images/tuckin-plated-desserts.jpg" />
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#homeCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#homeCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>  
</div>
<div class="row">
    <div class="col-md-12">
        <h2>Welcome to the menu for the Western Oregon University Deli</h2>
        <p>This site is currently under construction, feel free to check out our work-in-progress menu.</p>
    </div>
</div>

source/Deli Menu/Deli Menu/Views/Home/Item.cshtml
@model Deli_Menu.Models.FoodItem

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4> @Html.DisplayFor(model => model.ItemName)</h4>
        <hr />
        <h5>@Html.DisplayFor(model => model.Calories) Calories</h5>
        <p>Servings per container: @Html.DisplayFor(model => model.ServingsContained)</p>
        <p><strong> Serving Size: @Html.DisplayFor(model => model.ServingSize)</strong></p>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TotalFat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TotalFat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SaturatedFat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SaturatedFat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TransFat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TransFat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Colesterol)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Colesterol)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sodium)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Sodium)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TotalCarbohydrate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TotalCarbohydrate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DietaryFiber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DietaryFiber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TotalSugars)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TotalSugars)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AddedSugars)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AddedSugars)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Protien)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Protien)
            </dd>
        </dl>
        <h5>Vitamins and Minerals</h5>
        <dl class="dl-horizontal">
            @*If there is vitamin A, render the information for it*@
            @if (Model.A != null)
             {

                    <dt>
                        @Html.DisplayNameFor(model => model.A)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.A)
                    </dd>
                }
            @*If there is vitamin C, render the information for it*@
            @if (Model.C != null)
             {
                <dt>
                    @Html.DisplayNameFor(model => model.C)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.C)
                </dd>
             }

            @*If there is Calcium, render the information for it*@
            @if (Model.Calcuim != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Calcuim)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Calcuim)
                </dd>
            }
            @*If there is Iron, render the information for it*@
            @if (Model.Iron != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Iron)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Iron)
                </dd>
            }
            @*If there is vitamin D, render the information for it*@
            @if (Model.D != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.D)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.D)
                </dd>
            }

            @*If there is vitamin E, render the information for it*@
            @if (Model.E != null) { 
                <dt>
                    @Html.DisplayNameFor(model => model.E)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.E)
                </dd>
            }

            @*If there is vitamin K, render the information for it*@
            @if (Model.K != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.K)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.K)
                </dd>
            }

            @*If there is Thiamin, render the information for it*@
            @if (Model.Thiamin != null) { 
                <dt>
                    @Html.DisplayNameFor(model => model.Thiamin)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Thiamin)
                </dd>
            }

            @*If there is Ribolavin, render the information for it*@
            @if (Model.Ribolavin != null) { 
                <dt>
                    @Html.DisplayNameFor(model => model.Ribolavin)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Ribolavin)
                </dd>
            }
            @*If there is Niacin, render the information for it*@
            @if (Model.Niacin != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Niacin)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Niacin)
                </dd>
            }
            @*If there is Folate, render the information for it*@
            @if (Model.Folate != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Folate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Folate)
                </dd>
            }

            @*If there is vitamin B12, render the information for it*@
            @if (Model.B12 != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.B12)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.B12)
                </dd>
            }

            @*If there is Biotin, render the information for it*@
            @if (Model.Biotin != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Biotin)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Biotin)
                </dd>
            }

            @*If there is Pantothenic Acid, render the information for it*@
            @if (Model.PantothenicAcid != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.PantothenicAcid)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PantothenicAcid)
                </dd>
            }
            @*If there is Phosphorus, render the information for it*@
            @if (Model.Phosphorus != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Phosphorus)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Phosphorus)
                </dd>
            }

            @*If there is Iodine, render the information for it*@
            @if (Model.Iodine != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Iodine)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Iodine)
                </dd>
            }
            @*If there is Magnesium, render the information for it*@
            @if (Model.Magnesium != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Magnesium)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Magnesium)
                </dd>
            }

            @*If there is Zinc render the information for it*@
            @if (Model.Zinc != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Zinc)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Zinc)
                </dd>
            }
            @*If there is Selenium, render the information for it*@
            @if (Model.Selenium != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Selenium)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Selenium)
                </dd>
            }
            @*If there is Copper, render the information for it*@
            @if (Model.Copper != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Copper)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Copper)
                </dd>
             }
            @*If there is Manganese, render the information for it*@
            @if (Model.Manganese != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Manganese)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Manganese)
                </dd>
            }

            @*If there is Chromium, render the information for it*@
            @if (Model.Chromium != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Chromium)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Chromium)
                </dd>
             }
            @*If there is Molybdenum, render the information for it*@
            @if (Model.Molybdenum != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Molybdenum)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Molybdenum)
                </dd>
            }

            @*If there is Chloride, render the information for it*@
            @if (Model.Chloride != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Chloride)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Chloride)
                </dd>

             }
        </dl>
        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.Ingredients)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ingredients)
            </dd>

        </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Menu")
</p>

source/Deli Menu/Deli Menu/Views/Home/Menu.cshtml
@model IEnumerable<Deli_Menu.Models.FoodItem>
@{
    ViewBag.Title = "Menu";
}

<h2>Menu</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ServingSize)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ServingsContained)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Calories)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalFat)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ItemName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServingSize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServingsContained)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Calories)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalFat)
            </td>
            <td>
                @Html.ActionLink("Item Information", "Item", new { id = item.ID })
            </td>
        </tr>
    }

</table>